apiVersion: v1
kind: Service
metadata:
  name: zlipper-backend-service
spec:
  type: NodePort
  selector:
    app: zlipper-backend
  ports:
    - protocol: TCP
      port: 4567
      targetPort: 4567
      nodePort: 30081 
