apiVersion: apps/v1
kind: Deployment
metadata:
  name: zlipper-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zlipper-backend
  template:
    metadata:
      labels:
        app: zlipper-backend
    spec:
      containers:
        - name: zlipper-backend
          image: zlipper-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4567
          env:
            - name: ALLOWED_ORIGINS
              value: "http://localhost:8080"
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
            - name: zips
              mountPath: /app/zips
          livenessProbe:
            httpGet:
              path: /health
              port: 4567
            initialDelaySeconds: 5
            periodSeconds: 5 # reduced from 10 to 5
            failureThreshold: 3 # Added failureThreshold to restart after 3 failures
          readinessProbe:
            httpGet:
              path: /health
              port: 4567
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3 # Added failureThreshold to restart after 3 failures
          resources:
            requests:
              cpu: "200m" # Request 200 milli-cores of CPU
              memory: "256Mi" # Request 256 MiB of memory
            limits:
              cpu: "500m" # Limit to 500 milli-cores of CPU
              memory: "512Mi" # Limit to 512 MiB of memory
      volumes:
        - name: uploads
          emptyDir: {}
        - name: zips
          emptyDir: {}
      restartPolicy: Always # Added restartPolicy
